### ISSUE TITLE
Review techs fancy upgrades

### ISSUE THREAD

**Issue by ThibaultRT** [tgardner/UniEngine#6]
![image](https://user-images.githubusercontent.com/36445760/88066610-3dafe480-cb6e-11ea-91f1-a628750c4612.png)

laser tech getting +5% to weapon damage of ships/def using laser tech

interesting idea but complexifies battle engine

To be decided

**Comment by ThibaultRT** [comment]
Here is the detailed list and proposal to keep/change :

- Laser technology increase by 5% the weapons of ships/defences using laser weapons
- Ion technology increase by 5% the weapons of ships/defences using Ion weapons
- Plasma technology increase by 5% the weapons of ships/defences using Plasma weapons
- Graviton technology increase by 5% the weapons of ships/defences using Graviton weapons (fancy stuff here)

I suggest to remove all of them to keep the battle sim matching current Ogame online simulators
@tgardner  just let me know if you're  OK then I delete and push a PR

**Comment by tgardner** [comment]
Yeah I agree, keep it the same as ogame. I'm going to be using speedsim as the basis for the battle engine implementation
